version: "3.8"
services:
  user-service:
    build: user-service
    ports:
      - "8080:8080"
  account-service:
    build: account-service
    ports:
      - "8082:8080"
  user-service-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
    expose:
      - "5432"
    volumes:
      - user-service-db:/var/lib/postgresql/data
  account-service-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=accounts
    expose:
      - "5432"
    volumes:
      - account-service-db:/var/lib/postgresql/data
volumes:
  user-service-db:
  account-service-db: